version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookapi
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_DATABASE: bookapi
      DB_USERNAME: app
      DB_PASSWORD: password
    volumes:
      - ./API:/var/www
    depends_on:
      - db
    expose:
      - 9000

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: client
    restart: unless-stopped
    volumes:
      - ./Client:/usr/src/app
    expose:
      - 3000

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - client
      - api

volumes:
  db_data:
